property_codes = {
    "elastic modulus (11-axis)": "",
    "elastic modulus (22-axis)": "",
    "elastic modulus (33-axis)": "",
    "thermal expansion coefficient (11-axis)": "",
    "thermal expansion coefficient (22-axis)": "",
    "thermal expansion coefficient (33-axis)": "",
    "reference temperature": "",
    "poisson's ratio (12-axis)": "",
    "poisson's ratio (23-axis)": "",
    "poisson's ratio (31-axis)": "",
    "shear modulus (12-axis)": "",
    "shear modulus (23-axis)": "",
    "shear modulus (31-axis)": "",
    "coefficient of friction": "",
    "density": "",
    "specific heat capacity": "",
    "enthalpy": "",
    "thermal conductivity (11-axis)": "",
    "thermal conductivity (22-axis)": "",
    "thermal conductivity (33-axis)": "",
    "convection coefficient": "",
    "emissivity": "",
    "heat generation rate": "",
    "viscosity": "",
    "speed of sound": "",
    "electrical resistivity (11-axis)": "",
    "electrical resistivity (22-axis)": "",
    "electrical resistivity (33-axis)": "",
    "electric relative permittivity (11-axis)": "",
    "electric relative permittivity (22-axis)": "",
    "electric relative permittivity (33-axis)": "",
    "magnetic relative permeability (11-axis)": "",
    "magnetic relative permeability (22-axis)": "",
    "magnetic relative permeability (33-axis)": "",
    "magnetic coercive force (11-axis)": "",
    "magnetic coercive force (22-axis)": "",
    "magnetic coercive force (33-axis)": "",
    "dielectric loss tangent": "",
    "seebeck coefficient (11-axis)": "",
    "seebeck coefficient (22-axis)": "",
    "seebeck coefficient (33-axis)": "",
}
