property_codes = {
    "elastic modulus (11-axis)": "EX",
    "elastic modulus (22-axis)": "EY",
    "elastic modulus (33-axis)": "EZ",
    "thermal expansion coefficient (11-axis)": "CTEX",
    "thermal expansion coefficient (22-axis)": "CTEY",
    "thermal expansion coefficient (33-axis)": "CTEZ",
    "reference temperature": "REFT",
    "poisson's ratio (12-axis)": "PRXY",
    "poisson's ratio (23-axis)": "PRYZ",
    "poisson's ratio (31-axis)": "PRXZ",
    "shear modulus (12-axis)": "GXY",
    "shear modulus (23-axis)": "GYZ",
    "shear modulus (31-axis)": "GXZ",
    "coefficient of friction": "MU",
    "density": "DENS",
    "specific heat capacity": "C",
    "enthalpy": "ENTH",
    "thermal conductivity (11-axis)": "KXX",
    "thermal conductivity (22-axis)": "KYY",
    "thermal conductivity (33-axis)": "KZZ",
    "convection coefficient": "HF",
    "emissivity": "EMIS",
    "heat generation rate": "QRATE",
    "viscosity": "VISC",
    "speed of sound": "SONC",
    "electrical resistivity (11-axis)": "RSVX",
    "electrical resistivity (22-axis)": "RSVY",
    "electrical resistivity (33-axis)": "RSVZ",
    "electric relative permittivity (11-axis)": "PERX",
    "electric relative permittivity (22-axis)": "PERY",
    "electric relative permittivity (33-axis)": "PERZ",
    "magnetic relative permeability (11-axis)": "MURX",
    "magnetic relative permeability (22-axis)": "MURY",
    "magnetic relative permeability (33-axis)": "MURZ",
    "magnetic coercive force (11-axis)": "MGXX",
    "magnetic coercive force (22-axis)": "MGYY",
    "magnetic coercive force (33-axis)": "MGZZ",
    "dielectric loss tangent": "LSST",
    "seebeck coefficient (11-axis)": "SBKX",
    "seebeck coefficient (22-axis)": "SBKY",
    "seebeck coefficient (33-axis)": "SBKZ",
}
